apiVersion: apps/v1
kind: Deployment
metadata:
  name: greencart-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greencart-backend
  template:
    metadata:
      labels:
        app: greencart-backend
    spec:
      containers:
      - name: backend
        image: swkariyawasam/greencart-backend:latest
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://host.docker.internal:5432/greencart"
          - name: SPRING_DATASOURCE_USERNAME
            value: "postgres"  
          - name: SPRING_DATASOURCE_PASSWORD
            value: "admin" 
          - name: SPRING_JPA_DATABASE_PLATFORM
            value: "org.hibernate.dialect.PostgreSQLDialect"
---
apiVersion: v1
kind: Service
metadata:
  name: greencart-backend-service
spec:
  type: LoadBalancer
  selector:
    app: greencart-backend
  ports:
    - port: 8080
      targetPort: 8080